{% set name = "pydantic_factories" %}
{% set version = "1.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic-factories-{{ version }}.tar.gz
  sha256: 21b41179fde971e3ffc934a7a3c55b201f51018923c267d4c0ebd014fad30404

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry-core >=1.0.0
  run:
    - xeger >=0.3.5,<1.0.0
    - faker
    - pydantic
    - python >=3.6,<4.0
    - typing-extensions

test:
  imports:
    - pydantic_factories
    - pydantic_factories.constraints
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Goldziher/pydantic-factories
  summary: Mock data generation for pydantic based models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
    - ivergara
